# Name your project! Use only lowercase letters and underscores.
# This should reflect your org or the project's purpose.
name: 'dbt_project_blueprint'
version: '1.0.0'

# Specifies which dbt profile to use for connection settings.
profile: 'dbt_project_blueprint'

# Paths where dbt will look for various types of files.
# Typically no need to change these unless using a custom structure.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Folders to be deleted when running `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_project_blueprint:
    10_bronze_layer:  # Raw or minimally processed data
      materialized: table
      +database: datawarehouse
      +schema: bronze
    20_silver_layer:  # Cleaned and transformed data
      materialized: table
      +database: datawarehouse
      +schema: silver
    30_gold_layer:  # Final, business-ready data
      materialized: view
      +database: datawarehouse
      +schema: gold

# Configuration for seed data (CSV files)
seeds:
  +database: datawarehouse
  +schema: bronze  # Seed data is loaded into the bronze layer
